In [14]:
import torch

x = torch.arange(4.0)
print(x)

x.requires_grad_(True) # 设置把x的梯度保存下来,y关于x的导数是放在这里的
print(x.grad)

y = 2 * torch.dot(x, x)
y.backward() #调用反向传播函数,意思是给你求个导
print(x.grad == 4 * x)

# x.grad.zero_() #下划线表示重写里面的内容 这里没有累计梯度,直接用会报错
y = x.sum()
y.backward()  
print(x.grad) #x.gard 是x的导数,求导

x.grad.zero_()
y = x * x
y.sum().backward()
print(x.grad)

x.grad.zero_()
y = x * x
u = y.detach() # 把y当做一个常数,丢掉y跟x的函数关系,用u保存
z = u * x
z.sum().backward()
print(x.grad == u)

tensor([0., 1., 2., 3.])
None
tensor([True, True, True, True])
tensor([ 1.,  5.,  9., 13.])
tensor([0., 2., 4., 6.])
tensor([True, True, True, True])
