In [4]:
import torch

x = torch.arange(12)
print(x)

print(x.shape)

# number of element
print(x.numel())

x.reshape(3, 4)
x

y = torch.zeros((2, 3, 4))
print(y)

z = torch.ones((2, 3, 4))
print(z)

# the element number of outside to inside 
k = torch.tensor([[[2,1,3], [5,6,4]],[[2,6,4],[2,3,6]]])
print(k)
print(k.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[2, 1, 3],
         [5, 6, 4]],

        [[2, 6, 4],
         [2, 3, 6]]])
torch.Size([2, 2, 3])
