In [1]:
import torch

x = torch.arange(12)
print(x)

print(x.shape)

# number of element
print(x.numel())

x = x.reshape(3, 4)
print(x)

y = torch.zeros((2, 3, 4))
print(y)

z = torch.ones((2, 3, 4))
print(z)

# the element number of outside to inside 
k = torch.tensor([[[2,1,3], [5,6,4]],[[2,6,4],[2,3,6]]])
print(k)
print(k.shape)

# exp(x) = e^x
print(torch.exp(k))

# cat : merge with dim = ? , which lay to merge by the number with outside to inside 
x = torch.arange(12, dtype = torch.float32).reshape((3, 4))
y = torch.tensor([[1.0,2,5,6],[1,2,3,4],[4,5,6,7]])
z = torch.cat((x, y), dim = 0)
print(z)
z = torch.cat((x, y), dim = 1)
print(z)

# the sum of the elements in x
print(x.sum())

x = torch.arange(12).reshape((3, 4))
y = torch.arange(12).reshape((3, 4))
print(id(x))
x += y
print(id(x))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[2, 1, 3],
         [5, 6, 4]],

        [[2, 6, 4],
         [2, 3, 6]]])
torch.Size([2, 2, 3])
tensor([[[  7.3891,   2.7183,  20.0855],
         [148.4132, 403.4288,  54.5981]],

        [[  7.3891, 403.4288,  54.5981],
         [  7.3891,  20.0855, 403.4288]]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  5.,  6.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.]])
tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  5.,  6.],
       

In [23]:
import os

os.makedirs(os.path.join('.', 'src',), exist_ok=True)
data_file = os.path.join('.', 'src', 'test.csv') # Comma-Separated Values
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd

data = pd.read_csv('./src/test.csv')
print(data)

inputs, inputs1, outputs = data.iloc[:, 0], data.iloc[:,1], data.iloc[:, 2]

inputs = inputs.fillna(inputs.mean())
print(inputs)

inputs1 = pd.get_dummies(inputs1, dummy_na = True, dtype=int)
print(inputs1)

import torch
X, y, z = torch.tensor(inputs.values), torch.tensor(inputs1.values), torch.tensor(outputs.values)
X, y, z

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
0    3.0
1    2.0
2    4.0
3    3.0
Name: NumRooms, dtype: float64
   Pave  NaN
0     1    0
1     0    1
2     0    1
3     0    1


(tensor([3., 2., 4., 3.], dtype=torch.float64),
 tensor([[1, 0],
         [0, 1],
         [0, 1],
         [0, 1]], dtype=torch.int32),
 tensor([127500, 106000, 178100, 140000]))